name: Deploy Salesforce Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@2.71.6
          sf --version

      - name: Install Git Delta Plugin
        run: |
          echo y | sf plugins install sfdx-git-delta@5.38.0

      - name: Create JWT Key File
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          chmod 600 server.key

      - name: Authenticate
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --alias prodOrg

      - name: Generate Delta Package
        run: |
          mkdir delta

          sf sgd source delta \
            --from HEAD~1 \
            --to HEAD \
            --output delta

      - name: Deploy Changed Components
        run: |
          sf project deploy start \
            --manifest delta/package/package.xml \
            --target-org prodOrg \
            --test-level RunLocalTests \
            --wait 60

      - name: Deploy Destructive Changes
        run: |
          if [ -f delta/destructiveChanges/destructiveChanges.xml ]; then

            sf project deploy start \
              --manifest delta/package/package.xml \
              --post-destructive-changes delta/destructiveChanges/destructiveChanges.xml \
              --target-org prodOrg \
              --wait 60

          fi